export const projects = [
  {
    title: "Labskill",
    status: "completed",
    ownStatus: "Company's property",
    short_description:
      "An online education platform especially in the IT field",
    description: "Labskill is an online education platform that focuses on IT skills. It provides various courses and training programs to help individuals enhance their technical abilities and knowledge in the field of information technology.",
    site: "https://Labskill.co",
    url: "/projects/labskill",
    imageUrl: "/card/labskill.png",
    restricted_reason: "",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Go", icon: "skill-icons:golang" },
    ],
  },
  {
    title: "Kawanstudy",
    status: "completed",
    ownStatus: "Company's property",
    short_description: "An online language learning platform",
    description: "Kawanstudy is an online language learning platform that offers courses and resources for individuals looking to improve their language skills. It provides a user-friendly interface and interactive features to enhance the learning experience.",
    site: "https://Kawanstudy.com",
    url: "/projects/kawanstudy",
    imageUrl: "/card/kawanstudy.png",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Go", icon: "skill-icons:golang" },
    ],
  },
  {
    title: "Sistem Informasi Perpustakaan UNP",
    status: "completed",
    ownStatus: "Company's property",
    short_description: "A web-based library system for UNP",
    description: "Sistem Informasi Perpustakaan UNP is a web-based library system designed for Universitas Negeri Padang (UNP). It provides features for managing library resources, user accounts, and borrowing transactions.",
    site: "restricted",
    url: "/projects/unp-library",
    imageUrl: "/card/unp-lib.png",
    restricted_reason: "Updated",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Node.js", icon: "devicon:nodejs" },
    ],
  },
  {
    title: "Katalog UNP",
    status: "completed",
    ownStatus: "Company's property",
    short_description:
      "A web-based catalog system for searching thesis and dissertation",
    description: "Katalog UNP is a web-based catalog system that allows users to search for thesis and dissertation documents from Universitas Negeri Padang (UNP). It provides a user-friendly interface for browsing and accessing academic resources.",
    site: "restricted",
    url: "/projects/katalog-unp",
    imageUrl: "/card/katalog-unp.png",
    restricted_reason: "Deployed in private server",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Node.js", icon: "devicon:nodejs" },
    ],
  },
  {
    title: "Ecoguard",
    status: "pending",
    ownStatus: "Private property",
    short_description: "Waste management system for density and volume",
    description: " Ecoguard is a waste management system that focuses on monitoring and managing waste density and volume. It integrated with CNN(Convolutional Neural Network) for tracking waste levels and optimizing waste collection processes.",
    site: "restricted",
    url: "/projects/kawanstudy",
    imageUrl: "/card/ecoguard.png",
    restricted_reason: "Updated",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Flask", icon: "skill-icons:flask-light" },
    ],
  },
  {
    title: "Techmate",
    status: "pending",
    ownStatus: "Techmate team",
    short_description: "A web-based platform for hardware and software services",
    description: "Techmate is a web-based platform that provides hardware and software services. It offers a range of solutions for individuals and businesses looking to enhance their technology infrastructure.",
    site: "restricted",
    url: "/projects/techmate",
    imageUrl: "/card/techmate.png",
    restricted_reason: "Updated",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Laravel", icon: "devicon:laravel" },
    ],
  },
  {
    title: "PintarKUR",
    status: "pending",
    ownStatus: "My Bangkit Academy team",
    short_description: "Web-based platform to predict KUR loan eligibility",
    description: "PintarKUR is a web-based platform that predicts KUR (Kredit Usaha Rakyat) loan eligibility. It uses machine learning algorithms to analyze user data and provide insights into loan eligibility.",
    site: "restricted",
    url: "/projects/pintarkur",
    imageUrl: "/card/pintarkur.png",
    restricted_reason: "Updated",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Go", icon: "skill-icons:golang" },
    ],
  },
  {
    title: "Wash Out!",
    status: "pending",
    ownStatus: "Private property",
    short_description: "A web-based platform for car wash services",
    description: "Wash Out! is a web-based platform that offers car wash services. It provides a convenient way for users to schedule and manage car wash appointments.",
    site: "restricted",
    url: "/projects/washout",
    imageUrl: "/card/washout.png",
    restricted_reason: "Updated",
    languages: [
      { name: "Next.js", icon: "devicon:nextjs" },
      { name: "Flask", icon: "skill-icons:flask-light" },
    ],
  },
];